### ISSUE TITLE
Need DN to authenticate

### ISSUE THREAD

**Issue by matracine** [DerManoMann/ldap-auth-service-provider#15]
Hello,
context : openldap with anonymous bind for retrieve users.
First phase woking perfectly, the user is found in Ldap.
During second phase, check password bind, username must be complete DN and not only username (uid=myusername, ou=people, ...., c=FR, dc=myorg, dc=fr).
In LdapAuthenticationProvider code : $this->ldapAuth($token->getUserName(), $token->getCredentials()) is retrieving user name.
I have to change it to : $this->ldapAuth($user->getdn(), $token->getCredentials())

In service configuration, I added : 'attr' => array('dn' => 'dn') to retreive the DN.
Had to change also : 
                $user->$method($userData[$key][0]);
to              $user->$method($userData[$key]);
to be able to retrieve the DN. Is this a bug or did I miss something ?

**Comment by DerManoMann** [comment]
Could you try the branch I just pushed? The tests are failing but that is unrelated, IMO :)

The defaults added should just make it work...

**Comment by matracine** [comment]
Hello,
Thanks for this modification, but :
- I think this is introducing a BC break : this change the base feature, developpers using the old feature need to add an attr => array('MyAuthfield' => 'AuthName'); to override the default value you introduced.
- In my case, if I add 'attr' => array('dn'=>'dn'); the $user->getAuthName() method return a NULL (normal) but ldapAuth return true. Normal, because I allow anonymous bind... This allow existing users to login without password. A test in LdapAuthMethod to ensure login is not null can correct.

**Comment by DerManoMann** [comment]
Hmm, I'll have to think about that...

**Comment by DerManoMann** [comment]
I've separated the authName mapping from the custom attributes, so this should fix the conflict.
Also figured why the tests were failing.. :)

Could you please try again?

**Comment by matracine** [comment]
Works like a charm.
Tested with  "symfony/security": "^3.1" ;)
